import Head from "next/head";
import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
import Navbar from "./Components/Navbar";
import UpcomingEvents from "./Components/Upcoming";
import Gallery from './Components/Gallery';




const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar/>
      <div className={styles.container}>

        <section className={styles.hero} id="home">
          <div className={styles.intro}>
            <div className={styles.loading_text}>
              <span className={styles.LoadingWord}>P</span>
              <span className={styles.LoadingWord}>L</span>
              <span className={styles.LoadingWord}>A</span>
              <span className={styles.LoadingWord}>N</span>
              <span className={styles.LoadingWord}>N</span>
              <span className={styles.LoadingWord}>E</span>
              <span className={styles.LoadingWord}>R</span>
              <span className={styles.LoadingWord}>-</span>
              <span className={styles.LoadingWord}>X</span>
            </div>
                <span className={styles.logo_right}>
                    Students Group of VIT
                </span>
                  
          </div>

          <div className={styles.info}>
            Forget cookie-cutter events. We don't just plan parties; we craft immersive experiences that spark joy, create connections, and leave a lasting impression. Let us turn your ideas into extraordinary moments that your guests will rave about for years to come. Ready to elevate your celebration?
          </div>

          <a href="#" className={styles.btn}>Read More...</a>
        </section>

      </div>

      <UpcomingEvents/>
      <Gallery/>

      <section className={styles.Footer}>
        <div className={styles.FooterContainer}>

          <div className={styles.FooterBox}>
            <h3>Quick Links</h3>
            <Link href="/Events">Events</Link> 
            <Link href="/EventOrganiser">Event Organizer</Link>
            <Link href="/Upcoming Events">UpcomingEvents</Link> 
            <Link href="/Gallery">Gallery</Link>
          </div>

          <div className={styles.FooterBox}>
            <h3>Contact Info</h3>
            <a href="#">+91 9692500950</a>
            <a href="#">+91 9911755583</a>
            <a href="#">plannerX@gmail.com</a>
            <a href="#">arrsh@gmail.com</a>
            <a href="#">Bangalore, India - 560054</a>
          </div>

          <div className={styles.FooterBox}>
            <h3>Follow Us</h3>
            <a href="#">Facebook</a>
            <a href="#">Twitter</a>
            <a href="#">Instagram</a>
            <a href="#">LinkedIn</a>
          </div>

        </div>

        <div className={styles.Credit}>
          Created by <span>Planners</span> | All rights reserved
        </div>
      </section>

    </>
  );
}
